FROM nginx:1.10.1

# Maintainer
MAINTAINER reharik

# set WORKDIR
#WORKDIR /opt/app/current

COPY docker/nginx.conf /etc/nginx/nginx.conf

#RUN mkdir /usr/share/nginx/html
COPY app/dist /usr/share/nginx/html

VOLUME app/dist:/usr/share/nginx/html
